// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// kron_iv
arma::sp_mat kron_iv(int n, const arma::mat& u);
RcppExport SEXP _multiLMMsel_kron_iv(SEXP nSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(kron_iv(n, u));
    return rcpp_result_gen;
END_RCPP
}
// y_ij
int y_ij(int i, int j, const arma::ivec& nis);
RcppExport SEXP _multiLMMsel_y_ij(SEXP iSEXP, SEXP jSEXP, SEXP nisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nis(nisSEXP);
    rcpp_result_gen = Rcpp::wrap(y_ij(i, j, nis));
    return rcpp_result_gen;
END_RCPP
}
// z_ij
List z_ij(int i, int j, const arma::ivec& nis, int q);
RcppExport SEXP _multiLMMsel_z_ij(SEXP iSEXP, SEXP jSEXP, SEXP nisSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nis(nisSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(z_ij(i, j, nis, q));
    return rcpp_result_gen;
END_RCPP
}
// diag_ww
arma::mat diag_ww(const arma::mat& Z, int i, int j, int k, const arma::ivec& nis, int q);
RcppExport SEXP _multiLMMsel_diag_ww(SEXP ZSEXP, SEXP iSEXP, SEXP jSEXP, SEXP kSEXP, SEXP nisSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nis(nisSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(diag_ww(Z, i, j, k, nis, q));
    return rcpp_result_gen;
END_RCPP
}
// triple_sum_diag_ww
arma::mat triple_sum_diag_ww(const arma::mat& Z, const arma::ivec& nis, int m, int q);
RcppExport SEXP _multiLMMsel_triple_sum_diag_ww(SEXP ZSEXP, SEXP nisSEXP, SEXP mSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nis(nisSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(triple_sum_diag_ww(Z, nis, m, q));
    return rcpp_result_gen;
END_RCPP
}
// triple_sum_transform
arma::sp_mat triple_sum_transform(const arma::mat& Z, const arma::ivec& nis, int m, int d, int q);
RcppExport SEXP _multiLMMsel_triple_sum_transform(SEXP ZSEXP, SEXP nisSEXP, SEXP mSEXP, SEXP dSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nis(nisSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(triple_sum_transform(Z, nis, m, d, q));
    return rcpp_result_gen;
END_RCPP
}
// triple_sum_ww
arma::sp_mat triple_sum_ww(const arma::mat& Z, const arma::ivec& nis, int m, int d, int q);
RcppExport SEXP _multiLMMsel_triple_sum_ww(SEXP ZSEXP, SEXP nisSEXP, SEXP mSEXP, SEXP dSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nis(nisSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(triple_sum_ww(Z, nis, m, d, q));
    return rcpp_result_gen;
END_RCPP
}
// double_sum_y
arma::mat double_sum_y(const arma::mat& Y, const arma::mat& X, const arma::mat& beta, const arma::ivec& nis, int m, int d);
RcppExport SEXP _multiLMMsel_double_sum_y(SEXP YSEXP, SEXP XSEXP, SEXP betaSEXP, SEXP nisSEXP, SEXP mSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nis(nisSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(double_sum_y(Y, X, beta, nis, m, d));
    return rcpp_result_gen;
END_RCPP
}
// double_sum_z_b
arma::sp_mat double_sum_z_b(const arma::mat& Z, const arma::mat& sigmaB, const arma::ivec& nis, int m, int d, int q);
RcppExport SEXP _multiLMMsel_double_sum_z_b(SEXP ZSEXP, SEXP sigmaBSEXP, SEXP nisSEXP, SEXP mSEXP, SEXP dSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigmaB(sigmaBSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nis(nisSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(double_sum_z_b(Z, sigmaB, nis, m, d, q));
    return rcpp_result_gen;
END_RCPP
}
// triple_sum_y
arma::sp_mat triple_sum_y(const arma::mat& Y, const arma::mat& Z, const arma::mat& X, const arma::mat& beta, const arma::ivec& nis, int m, int d, int q);
RcppExport SEXP _multiLMMsel_triple_sum_y(SEXP YSEXP, SEXP ZSEXP, SEXP XSEXP, SEXP betaSEXP, SEXP nisSEXP, SEXP mSEXP, SEXP dSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nis(nisSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(triple_sum_y(Y, Z, X, beta, nis, m, d, q));
    return rcpp_result_gen;
END_RCPP
}
// cov_yi
arma::mat cov_yi(const arma::mat& Z, const arma::mat& sigmaB, const arma::mat& sigmaE, const arma::ivec& nis, int i, int d, int q);
RcppExport SEXP _multiLMMsel_cov_yi(SEXP ZSEXP, SEXP sigmaBSEXP, SEXP sigmaESEXP, SEXP nisSEXP, SEXP iSEXP, SEXP dSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigmaB(sigmaBSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sigmaE(sigmaESEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nis(nisSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(cov_yi(Z, sigmaB, sigmaE, nis, i, d, q));
    return rcpp_result_gen;
END_RCPP
}
// triple_sum_for_estimate
List triple_sum_for_estimate(const arma::mat& Y, const arma::mat& X, const arma::mat& Z, const arma::mat& beta, const arma::ivec& nis, int m, int d, int q, const List& active_set_mat, int n);
RcppExport SEXP _multiLMMsel_triple_sum_for_estimate(SEXP YSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP betaSEXP, SEXP nisSEXP, SEXP mSEXP, SEXP dSEXP, SEXP qSEXP, SEXP active_set_matSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::ivec& >::type nis(nisSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const List& >::type active_set_mat(active_set_matSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(triple_sum_for_estimate(Y, X, Z, beta, nis, m, d, q, active_set_mat, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_multiLMMsel_kron_iv", (DL_FUNC) &_multiLMMsel_kron_iv, 2},
    {"_multiLMMsel_y_ij", (DL_FUNC) &_multiLMMsel_y_ij, 3},
    {"_multiLMMsel_z_ij", (DL_FUNC) &_multiLMMsel_z_ij, 4},
    {"_multiLMMsel_diag_ww", (DL_FUNC) &_multiLMMsel_diag_ww, 6},
    {"_multiLMMsel_triple_sum_diag_ww", (DL_FUNC) &_multiLMMsel_triple_sum_diag_ww, 4},
    {"_multiLMMsel_triple_sum_transform", (DL_FUNC) &_multiLMMsel_triple_sum_transform, 5},
    {"_multiLMMsel_triple_sum_ww", (DL_FUNC) &_multiLMMsel_triple_sum_ww, 5},
    {"_multiLMMsel_double_sum_y", (DL_FUNC) &_multiLMMsel_double_sum_y, 6},
    {"_multiLMMsel_double_sum_z_b", (DL_FUNC) &_multiLMMsel_double_sum_z_b, 6},
    {"_multiLMMsel_triple_sum_y", (DL_FUNC) &_multiLMMsel_triple_sum_y, 8},
    {"_multiLMMsel_cov_yi", (DL_FUNC) &_multiLMMsel_cov_yi, 7},
    {"_multiLMMsel_triple_sum_for_estimate", (DL_FUNC) &_multiLMMsel_triple_sum_for_estimate, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_multiLMMsel(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
